[prompt_navigator_analyze_static_error]
temperature = 0
system = """
You are an experienced programming expert, skilled at analyzing code bugs and providing precise guidance for fixing them.
"""
user="""\
Here is a Python code snippet:
```
{{ code_recent_solution|trim }}
```
However, errors occurred during static analysis:
```
{{ error_str|trim }}
```
Briefly explain the identified bug(s) by analyzing the code and static errors.
Provide a step-by-step approach to fix the issues.
Keep the fix steps concise for minor issues, but provide more detailed steps if major revisions are required.

Your answer should be directly parsable as YAML. DO NOT output anything else.
The output must be a YAML object like this:
Example YAML output:
```yaml
what_went_wrong: |
  ...
fixed_flow: |
  ...
```
Answer:
```yaml
"""